version: "3.9"
services:
  api:
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 4000:5000
  db:
    container_name: solar-ts-postgres
    image: "postgres"
    ports:
      - 4444:5432
